-- 
--  This is file `test-loader.lua',
--  generated with the docstrip utility.
-- 
--  The original source files were:
-- 
--  luatexbase-loader.dtx  (with options: `testdummy')
--  
--  Written in 2009, 2010 by Manuel Pegourie-Gonnard and Elie Roux.
--  
--  This work is under the CC0 license.
--  See source file 'luatexbase-loader.dtx' for details.
--  
return true
-- 
--  End of File `test-loader.lua'.
